### ISSUE TITLE
Add List tab

### ISSUE THREAD

**Issue by santosemax** [EECE3093C/team-project-undefined-backEnd-#64]
Add a list tab to view the list without having the ability to add an item. This will just be a page used by the user to visualize their list.

**Comment by santosemax** [comment]
Created a list tab and page. This can be stylized in the future but for now this issue is closed. The user can now view this items alone on a single page.

**Comment by nehaAnnareddy** [comment]
Required functionality was added

<img width="1563" alt="image" src="https://user-images.githubusercontent.com/89593420/231026939-896cc4ba-8e2f-4d91-919c-8d6159ccfa16.png">
